# Generated by Django 4.0 on 2021-12-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('addressLine1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('addressLine2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('addressLine3', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pin', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('otp', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('cuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('mcid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('basePrice', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('finalPrice', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
                ('desc', models.TextField()),
                ('specification', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('pic1', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('pic2', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('pic3', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('pic4', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('pic5', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.brand')),
                ('mainCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('otp', models.IntegerField(blank=True, default=0, null=True)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('scid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcategory'),
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('shipping', models.IntegerField(blank=True, default=0, null=True)),
                ('final', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('q', models.TextField(default='')),
                ('mode', models.CharField(max_length=10)),
                ('time', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
                ('product', models.ManyToManyField(default=1, to='mainApp.Product')),
            ],
        ),
    ]
